name: Update GitHub Snake

on:
  schedule:
    - cron: '0 0 * * *'     # every day at 00:00 UTC
  push:
    branches: [ main, master ]

permissions:
  contents: write

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # - name: Generate light & dark SVG-only Snakes
      #   uses: Platane/snk/svg-only@v3
      #   with:
      #     github_user_name: ${{ github.repository_owner }}
      #     outputs: |
      #       # light-mode snake (RGB 89,65,0)
      #       output/github-snake-light.svg?palette=github-light&color_snake=89,65,0
      #       # dark-mode snake (uses GitHub’s dark palette)
      #       output/github-snake-dark.svg?palette=github-dark&color_snake=230,178,186
      - name: Generate light & dark SVG-only Snakes
        uses: lowlighter/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            # light-mode snake (RGB 89,65,0)
            output/github-snake-light.svg?palette=github-light&color_snake=89,65,0
            # dark-mode snake (uses GitHub’s dark palette)
            output/github-snake-dark.svg?palette=github-dark&color_snake=230,178,186


      - name: Commit updated snakes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output/github-snake-light.svg output/github-snake-dark.svg
          git commit -m "chore: update github-snake svgs" || echo "No changes to commit"
          git push
